name: CI
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno ci
      - name: Unit test
        run: deno task ci:test
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno ci
      - name: Check type
        if: always()
        run: deno task check-type-src
      - name: Check type
        if: always()
        run: deno task check-type-test
      - name: Check format
        if: always()
        run: deno task check-fmt
      - name: Publish-Jsr dry-run
        run: deno task publish:jsr-try
