name: CI
on:
  push:
    branches:
      - main
      - develop
      - feat/*
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node-version: [18, 20, 22]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: asnowc/actions@setup-node/v2
        with:
          node_v: ${{matrix.node-version}}
          pnpm_v: 9
          run_install: true
      - name: Unit test
        run: pnpm run ci:test
      - name: Build
        if: ${{matrix.node-version == 22 && github.ref_name == 'main'}}
        run: pnpm run ci:build
      - name: Check API
        if: ${{matrix.node-version == 22 && github.ref_name == 'main'}}
        run: pnpm run ci:api-extract
