name: CI
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node-version: [18, 20, 22]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: true
      - uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
          cache: pnpm
      - name: Unit test
        run: pnpm run ci:test
  check:
    if: ${{github.ref_name=='main'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: true
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - name: Build
        run: pnpm run ci:build
      - name: Check API
        run: pnpm run ci:api-extract
