name: CI
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node-version: [18, 20, 22]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: true
      - uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
          cache: pnpm
      - name: Unit test
        run: pnpm run ci:test
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: true
      - uses: denoland/setup-deno@v2
        with:
          deno_version: v2.x
      - name: Check type
        run: deno task check-type-src
      - name: Check type
        run: deno task check-type-test
      - name: Publish-Jsr dry-run
        run: npx jsr publish --dry-run
      - name: Check format
        run: deno task check-fmt
